version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_DB: debttrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"

  debttrack-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: debttrack-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq